# 02 — TMDB Enrichment

Enrich the MovieLens 100K movie list with metadata from the TMDB API: actors, directors, and genres.

**Pipeline:**
1. Load `u.item` from MovieLens
2. Parse title and year from the MovieLens title format
3. Search TMDB automatically for each movie
4. Identify and export failed matches
5. Load manual mapping for failed matches
6. Re-run enrichment using manual TMDB IDs
7. Save final enriched dataset

> See `docs/02_enrichment_approach.md` for the full design rationale.

## 0. Setup

In [24]:
import os
import json
import time
import requests
from tqdm import tqdm
from dotenv import load_dotenv

load_dotenv()

TMDB_API_KEY = os.environ["TMDB_API_KEY"]
TMDB_BASE = "https://api.themoviedb.org/3"

def tmdb_get(endpoint, params=None):
    url = f"{TMDB_BASE}/{endpoint}"
    response = requests.get(url, params={"api_key": TMDB_API_KEY, **(params or {})})
    response.raise_for_status()
    return response.json()

print("Ready.")

Ready.

## 1. Explore — Genre List
What genres does TMDB know about? This is a single call — we'll use this to map genre IDs to names later.

In [2]:
genres = tmdb_get("genre/movie/list")
print(json.dumps(genres, indent=2))

{
  "genres": [
    {
      "id": 28,
      "name": "Action"
    },
    {
      "id": 12,
      "name": "Adventure"
    },
    {
      "id": 16,
      "name": "Animation"
    },
    {
      "id": 35,
      "name": "Comedy"
    },
    {
      "id": 80,
      "name": "Crime"
    },
    {
      "id": 99,
      "name": "Documentary"
    },
    {
      "id": 18,
      "name": "Drama"
    },
    {
      "id": 10751,
      "name": "Family"
    },
    {
      "id": 14,
      "name": "Fantasy"
    },
    {
      "id": 36,
      "name": "History"
    },
    {
      "id": 27,
      "name": "Horror"
    },
    {
      "id": 10402,
      "name": "Music"
    },
    {
      "id": 9648,
      "name": "Mystery"
    },
    {
      "id": 10749,
      "name": "Romance"
    },
    {
      "id": 878,
      "name": "Science Fiction"
    },
    {
      "id": 10770,
      "name": "TV Movie"
    },
    {
      "id": 53,
      "name": "Thriller"
    },
    {
      "id": 10752,
      "name": "War"
    },
    {
      "id": 37,
      "name": "Western"
    }
  ]
}

## 2. Explore — Search a Movie
Search for a known movie by title and year. Inspect everything TMDB returns.

In [3]:
search_result = tmdb_get("search/movie", {"query": "Toy Story", "year": 1995})
print(json.dumps(search_result, indent=2))

{
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg",
      "genre_ids": [
        10751,
        35,
        16,
        12
      ],
      "id": 862,
      "title": "Toy Story",
      "original_language": "en",
      "original_title": "Toy Story",
      "overview": "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
      "popularity": 17.9048,
      "poster_path": "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
      "release_date": "1995-11-22",
      "softcore": false,
      "video": false,
      "vote_average": 7.972,
      "vote_count": 19793
    },
    {
      "adult": false,
      "backdrop_path": "/k7vO3lOOkxZ88Bieu5UQLEBKZOl.jpg",
      "genre_ids": [
        99
      ],
      "id": 711704,
      "title": "Making 'Toy Story'",
      "original_language": "en",
      "original_title": "Making 'Toy Story'",
      "overview": "Documentary of the making of the groundbreaking Disney/Pixar animated hit movie.",
      "popularity": 1.0595,
      "poster_path": "/s2vPOYtuOY3DMYTduRx0cOzDcWm.jpg",
      "release_date": "1995-12-02",
      "softcore": false,
      "video": false,
      "vote_average": 6.318,
      "vote_count": 11
    }
  ],
  "total_pages": 1,
  "total_results": 2
}

In [4]:
# Grab the TMDB ID from the top result — we'll use it in the next call
tmdb_id = search_result["results"][0]["id"]
print(f"TMDB ID for Toy Story: {tmdb_id}")

TMDB ID for Toy Story: 862

## 3. Explore — Movie Credits
Use the TMDB ID from above to fetch the full cast and crew. Inspect everything.

In [5]:
credits = tmdb_get(f"movie/{tmdb_id}/credits")
print(json.dumps(credits, indent=2))

{
  "id": 862,
  "cast": [
    {
      "adult": false,
      "gender": 2,
      "id": 31,
      "known_for_department": "Acting",
      "name": "Tom Hanks",
      "original_name": "Tom Hanks",
      "popularity": 12.6417,
      "profile_path": "/oFvZoKI6lvU03n4YoNGAll9rkas.jpg",
      "cast_id": 14,
      "character": "Woody (voice)",
      "credit_id": "52fe4284c3a36847f8024f95",
      "order": 0
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12898,
      "known_for_department": "Acting",
      "name": "Tim Allen",
      "original_name": "Tim Allen",
      "popularity": 3.3918,
      "profile_path": "/woWhZzFILVhYMAvsPL171HjMY0y.jpg",
      "cast_id": 15,
      "character": "Buzz Lightyear (voice)",
      "credit_id": "52fe4284c3a36847f8024f99",
      "order": 1
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7167,
      "known_for_department": "Acting",
      "name": "Don Rickles",
      "original_name": "Don Rickles",
      "popularity": 2.6658,
      "profile_path": "/iGMOVxIQoTPepRvqSCtRulfpx7u.jpg",
      "cast_id": 16,
      "character": "Mr. Potato Head (voice)",
      "credit_id": "52fe4284c3a36847f8024f9d",
      "order": 2
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12899,
      "known_for_department": "Acting",
      "name": "Jim Varney",
      "original_name": "Jim Varney",
      "popularity": 0.9608,
      "profile_path": "/zvBFmvKUrPvE6FW35O3RP4i1ZPp.jpg",
      "cast_id": 17,
      "character": "Slinky Dog (voice)",
      "credit_id": "52fe4284c3a36847f8024fa1",
      "order": 3
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12900,
      "known_for_department": "Acting",
      "name": "Wallace Shawn",
      "original_name": "Wallace Shawn",
      "popularity": 3.0442,
      "profile_path": "/wVaM1WlFKDce4esThwL4XtNLhOe.jpg",
      "cast_id": 18,
      "character": "Rex (voice)",
      "credit_id": "52fe4284c3a36847f8024fa5",
      "order": 4
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7907,
      "known_for_department": "Acting",
      "name": "John Ratzenberger",
      "original_name": "John Ratzenberger",
      "popularity": 1.7796,
      "profile_path": "/oRtDEOuIO1yDhTz5dORBdxXuLMO.jpg",
      "cast_id": 19,
      "character": "Hamm (voice)",
      "credit_id": "52fe4284c3a36847f8024fa9",
      "order": 5
    },
    {
      "adult": false,
      "gender": 1,
      "id": 8873,
      "known_for_department": "Acting",
      "name": "Annie Potts",
      "original_name": "Annie Potts",
      "popularity": 2.3362,
      "profile_path": "/hWIzkAH7jkSkxBfwdudxbSPxeno.jpg",
      "cast_id": 20,
      "character": "Bo Peep (voice)",
      "credit_id": "52fe4284c3a36847f8024fad",
      "order": 6
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1116442,
      "known_for_department": "Acting",
      "name": "John Morris",
      "original_name": "John Morris",
      "popularity": 0.3772,
      "profile_path": "/lSdNMhN3DoXEQJ37IeOD5mTMUQK.jpg",
      "cast_id": 26,
      "character": "Andy (voice)",
      "credit_id": "52fe4284c3a36847f8024fc1",
      "order": 7
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12901,
      "known_for_department": "Acting",
      "name": "Erik von Detten",
      "original_name": "Erik von Detten",
      "popularity": 1.4153,
      "profile_path": "/v0ruIqUUZqXRWTsuui5irfsHMJe.jpg",
      "cast_id": 22,
      "character": "Sid (voice)",
      "credit_id": "52fe4284c3a36847f8024fb1",
      "order": 8
    },
    {
      "adult": false,
      "gender": 1,
      "id": 12133,
      "known_for_department": "Acting",
      "name": "Laurie Metcalf",
      "original_name": "Laurie Metcalf",
      "popularity": 2.9323,
      "profile_path": "/ypAppMZ1Q99cBjtX4BAnZmWjVXe.jpg",
      "cast_id": 23,
      "character": "Mrs. Davis (voice)",
      "credit_id": "52fe4284c3a36847f8024fb5",
      "order": 9
    },
    {
      "adult": false,
      "gender": 2,
      "id": 8655,
      "known_for_department": "Acting",
      "name": "R. Lee Ermey",
      "original_name": "R. Lee Ermey",
      "popularity": 1.7631,
      "profile_path": "/aXFJlEGHlQT7bwxkKwq6Sx7PeEp.jpg",
      "cast_id": 24,
      "character": "Sergeant (voice)",
      "credit_id": "52fe4284c3a36847f8024fb9",
      "order": 10
    },
    {
      "adult": false,
      "gender": 1,
      "id": 12903,
      "known_for_department": "Acting",
      "name": "Sarah Freeman",
      "original_name": "Sarah Freeman",
      "popularity": 0.4195,
      "profile_path": null,
      "cast_id": 25,
      "character": "Hannah (voice)",
      "credit_id": "52fe4284c3a36847f8024fbd",
      "order": 11
    },
    {
      "adult": false,
      "gender": 2,
      "id": 37221,
      "known_for_department": "Acting",
      "name": "Penn Jillette",
      "original_name": "Penn Jillette",
      "popularity": 0.9134,
      "profile_path": "/lxMpWaVKyeqZCxENRo1wu13iSTS.jpg",
      "cast_id": 27,
      "character": "TV Announcer (voice)",
      "credit_id": "52fe4284c3a36847f8024fc5",
      "order": 12
    },
    {
      "adult": false,
      "gender": 2,
      "id": 19545,
      "known_for_department": "Acting",
      "name": "Jack Angel",
      "original_name": "Jack Angel",
      "popularity": 1.1824,
      "profile_path": "/5MsVwIULYJotUSbDs61uSJff7ei.jpg",
      "cast_id": 300,
      "character": "Shark / Rocky Gibraltar (voice)",
      "credit_id": "5aa599ad9251412787027f71",
      "order": 13
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1266092,
      "known_for_department": "Acting",
      "name": "Spencer Aste",
      "original_name": "Spencer Aste",
      "popularity": 0.1878,
      "profile_path": null,
      "cast_id": 301,
      "character": "Wounded Soldier (voice)",
      "credit_id": "5aa599edc3a3687bfc02cbf2",
      "order": 14
    },
    {
      "adult": false,
      "gender": 2,
      "id": 94038,
      "known_for_department": "Acting",
      "name": "Greg Berg",
      "original_name": "Greg Berg",
      "popularity": 0.5305,
      "profile_path": "/w5Cn5dc9Sci7rTtMfCmIqIJfMjX.jpg",
      "cast_id": 302,
      "character": "Local Announcer (voice)",
      "credit_id": "5aa59b229251412781026d69",
      "order": 15
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1202809,
      "known_for_department": "Acting",
      "name": "Lisa Bradley",
      "original_name": "Lisa Bradley",
      "popularity": 0.2182,
      "profile_path": null,
      "cast_id": 303,
      "character": "Kid (voice)",
      "credit_id": "5aa59b4e925141278d027723",
      "order": 16
    },
    {
      "adult": false,
      "gender": 0,
      "id": 134713,
      "known_for_department": "Acting",
      "name": "Kendall Cunningham",
      "original_name": "Kendall Cunningham",
      "popularity": 0.3395,
      "profile_path": null,
      "cast_id": 304,
      "character": "Kid (voice)",
      "credit_id": "5aa59b7b92514127840277c1",
      "order": 17
    },
    {
      "adult": false,
      "gender": 1,
      "id": 73016,
      "known_for_department": "Acting",
      "name": "Debi Derryberry",
      "original_name": "Debi Derryberry",
      "popularity": 1.3522,
      "profile_path": "/aCVgHnvGBw7ssZA9kl1Pnr5pJjU.jpg",
      "cast_id": 305,
      "character": "Aliens / Pizza Planet Announcer (voice)",
      "credit_id": "5aa59b8d0e0a26075a02c4d4",
      "order": 18
    },
    {
      "adult": false,
      "gender": 2,
      "id": 186614,
      "known_for_department": "Acting",
      "name": "Cody Dorkin",
      "original_name": "Cody Dorkin",
      "popularity": 0.4889,
      "profile_path": "/bfPK4w62WDqE9cpfmXd89LGpamS.jpg",
      "cast_id": 306,
      "character": "Kid (voice)",
      "credit_id": "5aa59bc0c3a3687c0c02aa21",
      "order": 19
    },
    {
      "adult": false,
      "gender": 2,
      "id": 84213,
      "known_for_department": "Acting",
      "name": "Bill Farmer",
      "original_name": "Bill Farmer",
      "popularity": 1.4493,
      "profile_path": "/lhezx68R12s5Bsv7d77BrQb7tWA.jpg",
      "cast_id": 310,
      "character": "Monotone Announcer (voice)",
      "credit_id": "5aa59c2e0e0a26075d02c5cd",
      "order": 20
    },
    {
      "adult": false,
      "gender": 2,
      "id": 1122227,
      "known_for_department": "Production",
      "name": "Craig Good",
      "original_name": "Craig Good",
      "popularity": 0.305,
      "profile_path": null,
      "cast_id": 311,
      "character": "Mission Control (voice)",
      "credit_id": "5aa59c62925141278d027807",
      "order": 21
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1017469,
      "known_for_department": "Acting",
      "name": "Gregory Grudt",
      "original_name": "Gregory Grudt",
      "popularity": 0.1207,
      "profile_path": null,
      "cast_id": 307,
      "character": "Kid (voice)",
      "credit_id": "5aa59bd0c3a3687bfc02cdf4",
      "order": 22
    },
    {
      "adult": false,
      "gender": 1,
      "id": 1217873,
      "known_for_department": "Acting",
      "name": "Danielle Judovits",
      "original_name": "Danielle Judovits",
      "popularity": 0.3297,
      "profile_path": "/5ecdzR76eyTDcaTGfLOWNeksUi6.jpg",
      "cast_id": 312,
      "character": "Burned Rag Doll (voice)",
      "credit_id": "5aa59c75925141277e02772d",
      "order": 23
    },
    {
      "adult": false,
      "gender": 0,
      "id": 1266095,
      "known_for_department": "Acting",
      "name": "Sam Lasseter",
      "original_name": "Sam Lasseter",
      "popularity": 0.0658,
      "profile_path": null,
      "cast_id": 308,
      "character": "Kid (voice)",
      "credit_id": "5aa59bde0e0a26074d0285ce",
      "order": 24
    },
    {
      "adult": false,
      "gender": 1,
      "id": 178710,
      "known_for_department": "Acting",
      "name": "Brittany Levenbrown",
      "original_name": "Brittany Levenbrown",
      "popularity": 0.2523,
      "profile_path": null,
      "cast_id": 309,
      "character": "Kid (voice)",
      "credit_id": "5aa59c0b0e0a26075402b8a5",
      "order": 25
    },
    {
      "adult": false,
      "gender": 1,
      "id": 214701,
      "known_for_department": "Acting",
      "name": "Sherry Lynn",
      "original_name": "Sherry Lynn",
      "popularity": 1.0094,
      "profile_path": "/cp7SYig9JVbBWgc2YD4wEUNQGzh.jpg",
      "cast_id": 162,
      "character": "Mom (voice)",
      "credit_id": "59f546f592514141ed005c7f",
      "order": 26
    },
    {
      "adult": false,
      "gender": 2,
      "id": 79020,
      "known_for_department": "Acting",
      "name": "Scott McAfee",
      "original_name": "Scott McAfee",
      "popularity": 0.2793,
      "profile_path": "/meKYkzavWpSg2KheDlMlUmZC4za.jpg",
      "cast_id": 313,
      "character": "Kid (voice)",
      "credit_id": "5aa59ca4c3a3687c2502c393",
      "order": 27
    },
    {
      "adult": false,
      "gender": 1,
      "id": 84493,
      "known_for_department": "Acting",
      "name": "Mickie McGowan",
      "original_name": "Mickie McGowan",
      "popularity": 1.2233,
      "profile_path": "/4K1HF10EvDjdaIoDAnWqFZjnmvk.jpg",
      "cast_id": 339,
      "character": "Sid's Mom (voice)",
      "credit_id": "5e6ea17eb1f68d0019d87b0f",
      "order": 28
    },
    {
      "adult": false,
      "gender": 2,
      "id": 166406,
      "known_for_department": "Acting",
      "name": "Ryan O'Donohue",
      "original_name": "Ryan O'Donohue",
      "popularity": 0.5197,
      "profile_path": null,
      "cast_id": 314,
      "character": "Kid (voice)",
      "credit_id": "5aa59cb20e0a26074b02c841",
      "order": 29
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7882,
      "known_for_department": "Writing",
      "name": "Jeff Pidgeon",
      "original_name": "Jeff Pidgeon",
      "popularity": 0.7144,
      "profile_path": "/t8LV9Y6s1qwQQNSRfo6GWEExffd.jpg",
      "cast_id": 315,
      "character": "Aliens / Robot / Mr. Spell (voice)",
      "credit_id": "5aa59cbf0e0a260760027438",
      "order": 30
    },
    {
      "adult": false,
      "gender": 2,
      "id": 61968,
      "known_for_department": "Acting",
      "name": "Patrick Pinney",
      "original_name": "Patrick Pinney",
      "popularity": 0.6663,
      "profile_path": "/b0jgxFRdzjwXnmLA0udvjzKEQO2.jpg",
      "cast_id": 316,
      "character": "Pizza Delivery Guy / Angry Driver #2 (voice)",
      "credit_id": "5aa59cce925141279302851e",
      "order": 31
    },
    {
      "adult": false,
      "gender": 2,
      "id": 61969,
      "known_for_department": "Acting",
      "name": "Phil Proctor",
      "original_name": "Phil Proctor",
      "popularity": 0.6692,
      "profile_path": "/wAfx3qAEvcsLpEEIP0zwdhuDIcW.jpg",
      "cast_id": 317,
      "character": "Pizza Planet Announcer / Pizza Planet Guard (voice)",
      "credit_id": "5aa59cdec3a3687c2502c3d9",
      "order": 32
    },
    {
      "adult": false,
      "gender": 2,
      "id": 157626,
      "known_for_department": "Acting",
      "name": "Jan Rabson",
      "original_name": "Jan Rabson",
      "popularity": 0.8158,
      "profile_path": "/8IBFupx53arTqxOYhGkGwyVSaOn.jpg",
      "cast_id": 318,
      "character": "Gas Station Attendant (voice)",
      "credit_id": "5aa59ced0e0a26075a02c62b",
      "order": 33
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7911,
      "known_for_department": "Writing",
      "name": "Joe Ranft",
      "original_name": "Joe Ranft",
      "popularity": 0.9322,
      "profile_path": "/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg",
      "cast_id": 319,
      "character": "Lenny the Binoculars (voice)",
      "credit_id": "5aa59cfa0e0a260760027472",
      "order": 34
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7,
      "known_for_department": "Writing",
      "name": "Andrew Stanton",
      "original_name": "Andrew Stanton",
      "popularity": 1.6277,
      "profile_path": "/fo6ePCWEVB0L1sccrvB99Iaoqcg.jpg",
      "cast_id": 320,
      "character": "Commercial Chorus (voice)",
      "credit_id": "5aa59d0bc3a3687bff02cc99",
      "order": 35
    },
    {
      "adult": false,
      "gender": 2,
      "id": 158124,
      "known_for_department": "Acting",
      "name": "Shane Sweet",
      "original_name": "Shane Sweet",
      "popularity": 0.4143,
      "profile_path": "/3fVAoIbfMO2XKtMsIOVpo5fkXVq.jpg",
      "cast_id": 321,
      "character": "Kid (voice)",
      "credit_id": "5aa59d18925141277e0277a1",
      "order": 36
    }
  ],
  "crew": [
    {
      "adult": false,
      "gender": 2,
      "id": 7879,
      "known_for_department": "Production",
      "name": "John Lasseter",
      "original_name": "John Lasseter",
      "popularity": 1.7034,
      "profile_path": "/xlrE4VD2VbZCDpaNdWCpH1ZihPS.jpg",
      "credit_id": "52fe4284c3a36847f8024f49",
      "department": "Directing",
      "job": "Director"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12891,
      "known_for_department": "Writing",
      "name": "Joss Whedon",
      "original_name": "Joss Whedon",
      "popularity": 1.2627,
      "profile_path": "/6PJwHV17KTuTRQaqrXBtVCwchcU.jpg",
      "credit_id": "52fe4284c3a36847f8024f4f",
      "department": "Writing",
      "job": "Screenplay"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7,
      "known_for_department": "Writing",
      "name": "Andrew Stanton",
      "original_name": "Andrew Stanton",
      "popularity": 1.6277,
      "profile_path": "/fo6ePCWEVB0L1sccrvB99Iaoqcg.jpg",
      "credit_id": "52fe4284c3a36847f8024f55",
      "department": "Writing",
      "job": "Screenplay"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12892,
      "known_for_department": "Writing",
      "name": "Joel Cohen",
      "original_name": "Joel Cohen",
      "popularity": 0.81,
      "profile_path": "/cCJDIvQatfefZtB9cI49S2L3erC.jpg",
      "credit_id": "52fe4284c3a36847f8024f5b",
      "department": "Writing",
      "job": "Screenplay"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12893,
      "known_for_department": "Writing",
      "name": "Alec Sokolow",
      "original_name": "Alec Sokolow",
      "popularity": 0.6348,
      "profile_path": "/8E33sB5x2XGtjde9ubs78hEhFe8.jpg",
      "credit_id": "52fe4284c3a36847f8024f61",
      "department": "Writing",
      "job": "Screenplay"
    },
    {
      "adult": false,
      "gender": 1,
      "id": 12894,
      "known_for_department": "Production",
      "name": "Bonnie Arnold",
      "original_name": "Bonnie Arnold",
      "popularity": 0.3712,
      "profile_path": "/fFU68wkvil1w8gOjwCzzHysKJP0.jpg",
      "credit_id": "52fe4284c3a36847f8024f67",
      "department": "Production",
      "job": "Producer"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12895,
      "known_for_department": "Production",
      "name": "Edwin Catmull",
      "original_name": "Edwin Catmull",
      "popularity": 0.3624,
      "profile_path": "/dRxY51eWnvSpTn1A2MQOwbnHDFE.jpg",
      "credit_id": "52fe4284c3a36847f8024f6d",
      "department": "Production",
      "job": "Executive Producer"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12896,
      "known_for_department": "Production",
      "name": "Ralph Guggenheim",
      "original_name": "Ralph Guggenheim",
      "popularity": 0.2041,
      "profile_path": "/3XhuBjcdE9hRZGQ4GyJ6h0mObig.jpg",
      "credit_id": "52fe4284c3a36847f8024f73",
      "department": "Production",
      "job": "Producer"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12897,
      "known_for_department": "Acting",
      "name": "Steve Jobs",
      "original_name": "Steve Jobs",
      "popularity": 0.3467,
      "profile_path": "/n71rW0xTowxKD0HwvLiWkaIfgbf.jpg",
      "credit_id": "52fe4284c3a36847f8024f79",
      "department": "Production",
      "job": "Executive Producer"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 8,
      "known_for_department": "Directing",
      "name": "Lee Unkrich",
      "original_name": "Lee Unkrich",
      "popularity": 0.8667,
      "profile_path": "/crb297utC6W4HSstOe5djDPTwEN.jpg",
      "credit_id": "52fe4284c3a36847f8024f8b",
      "department": "Editing",
      "job": "Editor"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7883,
      "known_for_department": "Art",
      "name": "Ralph Eggleston",
      "original_name": "Ralph Eggleston",
      "popularity": 0.257,
      "profile_path": "/28ZxW5tHMuWYK8T3I0xLfVAF9yw.jpg",
      "credit_id": "52fe4284c3a36847f8024f91",
      "department": "Art",
      "job": "Art Direction"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7911,
      "known_for_department": "Writing",
      "name": "Joe Ranft",
      "original_name": "Joe Ranft",
      "popularity": 0.9322,
      "profile_path": "/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg",
      "credit_id": "617c692bd388ae008a026b84",
      "department": "Writing",
      "job": "Story Supervisor"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 958881,
      "known_for_department": "Writing",
      "name": "Robert Lence",
      "original_name": "Robert Lence",
      "popularity": 0.5826,
      "profile_path": "/LaT44CeqJYQuN8SfDvbCyoA3kt.jpg",
      "credit_id": "617c69585294e7002a4ab452",
      "department": "Writing",
      "job": "Story Supervisor"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 7,
      "known_for_department": "Writing",
      "name": "Andrew Stanton",
      "original_name": "Andrew Stanton",
      "popularity": 1.6277,
      "profile_path": "/fo6ePCWEVB0L1sccrvB99Iaoqcg.jpg",
      "credit_id": "617c69725aba3200439f4f90",
      "department": "Art",
      "job": "Storyboard Artist"
    },
    {
      "adult": false,
      "gender": 2,
      "id": 12079,
      "known_for_department": "Directing",
      "name": "Kelly Asbury",
      "original_name": "Kelly Asbury",
      "popularity": 0.4622,

## 4. Load MovieLens `u.item`

In [6]:
import pandas as pd

# u.item is pipe-separated and uses Latin-1 encoding
columns = [
    "movieId", "title", "release_date", "video_release_date", "imdb_url",
    "unknown", "Action", "Adventure", "Animation", "Children", "Comedy",
    "Crime", "Documentary", "Drama", "Fantasy", "FilmNoir", "Horror",
    "Musical", "Mystery", "Romance", "SciFi", "Thriller", "War", "Western"
]

movies = pd.read_csv(
    "../data/raw/ml-100k/u.item",
    sep="|",
    names=columns,
    encoding="latin-1"
)

print(f"Shape: {movies.shape}")
movies[["movieId", "title", "imdb_url"]].head(10)

Shape: (1682, 24)

,movieId,title,imdb_url
0,1,Toy Story (1995),http://us.imdb.com/M/title-exact?Toy%20Story%2...
1,2,GoldenEye (1995),http://us.imdb.com/M/title-exact?GoldenEye%20(...
2,3,Four Rooms (1995),http://us.imdb.com/M/title-exact?Four%20Rooms%...
3,4,Get Shorty (1995),http://us.imdb.com/M/title-exact?Get%20Shorty%...
4,5,Copycat (1995),http://us.imdb.com/M/title-exact?Copycat%20(1995)
5,6,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...
6,7,Twelve Monkeys (1995),http://us.imdb.com/M/title-exact?Twelve%20Monk...
7,8,Babe (1995),http://us.imdb.com/M/title-exact?Babe%20(1995)
8,9,Dead Man Walking (1995),http://us.imdb.com/M/title-exact?Dead%20Man%20...
9,10,Richard III (1995),http://us.imdb.com/M/title-exact?Richard%20III...

In [7]:
# Inspect the IMDB URL format — this tells us if we can extract clean IDs
print("Sample IMDB URLs:")
for url in movies["imdb_url"].dropna().head(10):
    print(url)

Sample IMDB URLs:
http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)
http://us.imdb.com/M/title-exact?GoldenEye%20(1995)
http://us.imdb.com/M/title-exact?Four%20Rooms%20(1995)
http://us.imdb.com/M/title-exact?Get%20Shorty%20(1995)
http://us.imdb.com/M/title-exact?Copycat%20(1995)
http://us.imdb.com/Title?Yao+a+yao+yao+dao+waipo+qiao+(1995)
http://us.imdb.com/M/title-exact?Twelve%20Monkeys%20(1995)
http://us.imdb.com/M/title-exact?Babe%20(1995)
http://us.imdb.com/M/title-exact?Dead%20Man%20Walking%20(1995)
http://us.imdb.com/M/title-exact?Richard%20III%20(1995)

## 5. Parse Title and Year

In [9]:
import re

def parse_title_year(raw_title):
    # Extract year from the last (YYYY) at end of string
    year_match = re.search(r'\((\d{4})\)\s*$', raw_title)
    parsed_year = int(year_match.group(1)) if year_match else None

    # Strip the (YYYY) from the title
    title = re.sub(r'\s*\(\d{4}\)\s*$', '', raw_title).strip()

    # Uninvert articles: "Lambs, The" → "The Lambs"
    for article in ["An", "The", "A"]:
        suffix = f", {article}"
        if title.endswith(suffix):
            title = f"{article} {title[:-len(suffix)]}"
            break

    return title, parsed_year

In [10]:
movies[["parsed_title", "parsed_year"]] = movies["title"].apply(
    lambda t: pd.Series(parse_title_year(t))
)

print(f"Total movies:    {len(movies)}")
print(f"Missing year:    {movies['parsed_year'].isna().sum()}")

# Show inverted article fixes
inverted = movies[movies["title"].str.contains(r', (The|An|A) \(', regex=True, na=False)]
print(f"Inverted titles: {len(inverted)}")
print()
display(inverted[["title", "parsed_title", "parsed_year"]].head(10))

print("\nGeneral sample:")
display(movies[["title", "parsed_title", "parsed_year"]].sample(10, random_state=42))

Total movies:    1682
Missing year:    2
Inverted titles: 364

C:\Users\Diego Sanchez\AppData\Local\Temp\ipykernel_31332\339595093.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  inverted = movies[movies["title"].str.contains(r', (The|An|A) \(', regex=True, na=False)]

,title,parsed_title,parsed_year
11,"Usual Suspects, The (1995)",The Usual Suspects,1995.0
17,"White Balloon, The (1995)",The White Balloon,1995.0
24,"Birdcage, The (1996)",The Birdcage,1996.0
25,"Brothers McMullen, The (1995)",The Brothers McMullen,1995.0
33,"Doom Generation, The (1995)",The Doom Generation,1995.0
37,"Net, The (1995)",The Net,1995.0
51,"Madness of King George, The (1994)",The Madness of King George,1994.0
54,"Professional, The (1994)",The Professional,1994.0
62,"Santa Clause, The (1994)",The Santa Clause,1994.0
63,"Shawshank Redemption, The (1994)",The Shawshank Redemption,1994.0

General sample:

,title,parsed_title,parsed_year
1393,Swept from the Sea (1997),Swept from the Sea,1997.0
743,Michael Collins (1996),Michael Collins,1996.0
1605,Deceiver (1997),Deceiver,1997.0
49,Star Wars (1977),Star Wars,1977.0
188,"Grand Day Out, A (1992)",A Grand Day Out,1992.0
482,Casablanca (1942),Casablanca,1942.0
892,For Richer or Poorer (1997),For Richer or Poorer,1997.0
613,Giant (1956),Giant,1956.0
1627,Lamerica (1994),Lamerica,1994.0
1346,"Ballad of Narayama, The (Narayama Bushiko) (1958)","Ballad of Narayama, The (Narayama Bushiko)",1958.0

## 6. Automated TMDB Search

In [14]:
import time

SAMPLE_SIZE = 5
SLEEP_SECONDS = 0.25

sample = movies.head(SAMPLE_SIZE).copy()
results = []

for _, row in sample.iterrows():
    year = int(row["parsed_year"]) if pd.notna(row["parsed_year"]) else None
    response = tmdb_get("search/movie", {"query": row["parsed_title"], "year": year})

    hits = response.get("results", [])
    if hits:
        top = hits[0]
        results.append({
            "movieId":    row["movieId"],
            "raw_title":  row["title"],
            "tmdb_id":    top["id"],
            "tmdb_title": top["title"],
            "tmdb_year":  top.get("release_date", "")[:4],
            "matched":    True,
        })
    else:
        results.append({
            "movieId":    row["movieId"],
            "raw_title":  row["title"],
            "tmdb_id":    None,
            "tmdb_title": None,
            "tmdb_year":  None,
            "matched":    False,
        })

    time.sleep(SLEEP_SECONDS)

sample_results = pd.DataFrame(results)
display(sample_results)
print(f"\nMatched: {sample_results['matched'].sum()} / {len(sample_results)}")

   movieId          raw_title  tmdb_id  tmdb_title tmdb_year  matched
0        1   Toy Story (1995)      862   Toy Story      1995     True
1        2   GoldenEye (1995)      710   GoldenEye      1995     True
2        3  Four Rooms (1995)        5  Four Rooms      1995     True
3        4  Get Shorty (1995)     8012  Get Shorty      1995     True
4        5     Copycat (1995)     1710     Copycat      1995     True

Matched: 5 / 5

In [22]:
SLEEP_SECONDS = 0.25
enriched = []
failed = []

for row in tqdm(movies.itertuples(), total=len(movies), desc="Enriching"):
    year = int(row.parsed_year) if pd.notna(row.parsed_year) else None

    # Step 1: search by title + year
    response = tmdb_get("search/movie", {"query": row.parsed_title, "year": year})
    time.sleep(SLEEP_SECONDS)

    hits = response.get("results", [])
    if not hits:
        print(f"  ✗ No match: {row.title}")
        record = {
            "movieId":   row.movieId,
            "raw_title": row.title,
            "tmdb_id":   None,
            "genre_ids": [],
            "cast":      [],
            "directors": [],
            "matched":   False,
        }
        enriched.append(record)
        failed.append({"movieId": row.movieId, "raw_title": row.title,
                        "parsed_title": row.parsed_title, "parsed_year": year})
        continue

    top = hits[0]

    # Step 2: fetch credits using the matched tmdb_id
    credits = tmdb_get(f"movie/{top['id']}/credits")
    time.sleep(SLEEP_SECONDS)

    enriched.append({
        "movieId":   row.movieId,
        "raw_title": row.title,
        "tmdb_id":   top["id"],
        "genre_ids": top.get("genre_ids", []),
        "cast":      [m["name"] for m in credits.get("cast", [])[:10]],
        "directors": [m["name"] for m in credits.get("crew", []) if m["job"] == "Director"],
        "matched":   True,
    })

enriched_df = pd.DataFrame(enriched)
failed_df = pd.DataFrame(failed)

print(f"\nMatched: {enriched_df['matched'].sum()} / {len(enriched_df)}")
print(f"Failed:  {len(failed_df)}")
display(enriched_df.head())

Enriching:   0%|          | 0/1682 [00:00<?, ?it/s]

  ✗ No match: Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)
  ✗ No match: Dolores Claiborne (1994)
  ✗ No match: Brother Minister: The Assassination of Malcolm X (1994)
  ✗ No match: Return of the Pink Panther, The (1974)
  ✗ No match: Monty Python and the Holy Grail (1974)
  ✗ No match: Grand Day Out, A (1992)
  ✗ No match: Houseguest (1994)
  ✗ No match: Heavyweights (1994)
  ✗ No match: Red Rock West (1992)
  ✗ No match: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)
  ✗ No match: Stephen King's The Langoliers (1995)
  ✗ No match: Daniel Defoe's Robinson Crusoe (1996)
  ✗ No match: Conan the Barbarian (1981)
  ✗ No match: Canadian Bacon (1994)
  ✗ No match: Mute Witness (1994)
  ✗ No match: Beyond Bedlam (1993)
  ✗ No match: Swimming with Sharks (1995)
  ✗ No match: Boys Life (1995)
  ✗ No match: Power 98 (1995)
  ✗ No match: Loch Ness (1995)
  ✗ No match: Two or Three Things I Know About Her (1966)
  ✗ No match: Nosferatu a Venezia (1986)
  ✗ No match: Hearts and Minds (1996)
  ✗ No match: Time Tracers (1995)
  ✗ No match: U.S. Marshalls (1998)
  ✗ No match: Some Folks Call It a Sling Blade (1993)
  ✗ No match: Shiloh (1997)
  ✗ No match: Lay of the Land, The (1997)
  ✗ No match: Celestial Clockwork (1994)
  ✗ No match: It's My Party (1995)
  ✗ No match: Bloodsport 2 (1995)
  ✗ No match: Jupiter's Wife (1994)
  ✗ No match: Backbeat (1993)
  ✗ No match: Major Payne (1994)
  ✗ No match: Boys of St. Vincent, The (1993)
  ✗ No match: Marlene Dietrich: Shadow and Light (1996)
  ✗ No match: Poison Ivy II (1995)
  ✗ No match: Big Bang Theory, The (1994)
  ✗ No match: Bread and Chocolate (Pane e cioccolata) (1973)
  ✗ No match: Ayn Rand: A Sense of Life (1997)
  ✗ No match: New York Cop (1996)
  ✗ No match: Delta of Venus (1994)
  ✗ No match: Carmen Miranda: Bananas Is My Business (1994)
  ✗ No match: Low Life, The (1994)
  ✗ No match: Last Klezmer: Leopold Kozlowski, His Life and Music, The (1995)
  ✗ No match: Story of Xinghua, The (1993)
  ✗ No match: Day the Sun Turned Cold, The (Tianguo niezi) (1994)
  ✗ No match: For the Moment (1994)
  ✗ No match: The Deadly Cure (1996)
  ✗ No match: Boys in Venice (1996)
  ✗ No match: Forbidden Christ, The (Cristo proibito, Il) (1950)
  ✗ No match: Hurricane Streets (1998)
  ✗ No match: Ciao, Professore! (1993)
  ✗ No match: Boy's Life 2 (1997)
  ✗ No match: Land Before Time III: The Time of the Great Giving (1995) (V)
  ✗ No match: Gilligan's Island: The Movie (1998)
  ✗ No match: Men of Means (1998)
  ✗ No match: Nina Takes a Lover (1994)
  ✗ No match: Jerky Boys, The (1994)
  ✗ No match: Farmer & Chase (1995)
  ✗ No match: Aiqing wansui (1994)
  ✗ No match: Being Human (1993)
  ✗ No match: Hostile Intentions (1994)
  ✗ No match: Promise, The (Versprechen, Das) (1994)
  ✗ No match: Vermont Is For Lovers (1992)
  ✗ No match: Vie est belle, La (Life is Rosey) (1987)
  ✗ No match: Invitation, The (Zaproszenie) (1986)
  ✗ No match: Duoluo tianshi (1995)
  ✗ No match: Magic Hour, The (1998)
  ✗ No match: Guantanamera (1994)
  ✗ No match: Hurricane Streets (1998)
  ✗ No match: Desert Winds (1995)
  ✗ No match: Silence of the Palace, The (Saimt el Qusur) (1994)
  ✗ No match: Á köldum klaka (Cold Fever) (1994)
  ✗ No match: Etz Hadomim Tafus (Under the Domin Tree) (1994)
  ✗ No match: Bitter Sugar (Azucar Amargo) (1996)
  ✗ No match: Next Step, The (1995)
  ✗ No match: Further Gesture, A (1996)

Matched: 1604 / 1682
Failed:  78

,movieId,raw_title,tmdb_id,genre_ids,cast,directors,matched
0,1,Toy Story (1995),862.0,"[10751, 35, 16, 12]","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",[John Lasseter],True
1,2,GoldenEye (1995),710.0,"[12, 28, 53]","[Pierce Brosnan, Sean Bean, Izabella Scorupco,...",[Martin Campbell],True
2,3,Four Rooms (1995),5.0,[35],"[Tim Roth, Jennifer Beals, David Proval, Ione ...","[Allison Anders, Alexandre Rockwell, Quentin T...",True
3,4,Get Shorty (1995),8012.0,"[35, 53, 80]","[John Travolta, Gene Hackman, Rene Russo, Dann...",[Barry Sonnenfeld],True
4,5,Copycat (1995),1710.0,"[53, 80, 9648]","[Sigourney Weaver, Holly Hunter, Dermot Mulron...",[Jon Amiel],True

In [25]:
SLEEP_SECONDS = 0.25
retry_enriched = []
still_failed = []

for row in tqdm(failed_df.itertuples(), total=len(failed_df), desc="Retrying"):
    # Search by title only — drop the year constraint
    response = tmdb_get("search/movie", {"query": row.parsed_title})
    time.sleep(SLEEP_SECONDS)

    hits = response.get("results", [])
    if not hits:
        print(f"  ✗ Still no match: {row.raw_title}")
        still_failed.append({"movieId": row.movieId, "raw_title": row.raw_title,
                              "parsed_title": row.parsed_title, "parsed_year": row.parsed_year})
        continue

    top = hits[0]
    credits = tmdb_get(f"movie/{top['id']}/credits")
    time.sleep(SLEEP_SECONDS)

    print(f"  ✓ Recovered: {row.raw_title}  →  {top['title']} ({top.get('release_date', '')[:4]})")
    retry_enriched.append({
        "movieId":   row.movieId,
        "raw_title": row.raw_title,
        "tmdb_id":   top["id"],
        "genre_ids": top.get("genre_ids", []),
        "cast":      [m["name"] for m in credits.get("cast", [])[:10]],
        "directors": [m["name"] for m in credits.get("crew", []) if m["job"] == "Director"],
        "matched":   True,
    })

# Merge retried successes back into enriched_df
if retry_enriched:
    retried_df = pd.DataFrame(retry_enriched)
    recovered_ids = set(retried_df["movieId"])
    enriched_df = pd.concat([
        enriched_df[~enriched_df["movieId"].isin(recovered_ids)],
        retried_df
    ]).sort_values("movieId").reset_index(drop=True)

failed_df = pd.DataFrame(still_failed) if still_failed else pd.DataFrame()

print(f"\nRecovered: {len(retry_enriched)}")
print(f"Still failed: {len(failed_df)}")
print(f"Total matched: {enriched_df['matched'].sum()} / {len(enriched_df)}")

Retrying:   1%|▏         | 1/78 [00:00<00:54,  1.41it/s]

  ✗ Still no match: Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)

Retrying:   3%|▎         | 2/78 [00:02<01:23,  1.10s/it]

  ✓ Recovered: Dolores Claiborne (1994)  →  Dolores Claiborne (1995)

Retrying:   4%|▍         | 3/78 [00:03<01:29,  1.19s/it]

  ✓ Recovered: Brother Minister: The Assassination of Malcolm X (1994)  →  Brother Minister: The Assassination of Malcolm X (1995)

Retrying:   5%|▌         | 4/78 [00:04<01:33,  1.27s/it]

  ✓ Recovered: Return of the Pink Panther, The (1974)  →  The Return of the Pink Panther (1975)

Retrying:   6%|▋         | 5/78 [00:05<01:29,  1.23s/it]

  ✓ Recovered: Monty Python and the Holy Grail (1974)  →  Monty Python and the Holy Grail (1975)

Retrying:   8%|▊         | 6/78 [00:06<01:20,  1.12s/it]

  ✓ Recovered: Grand Day Out, A (1992)  →  A Grand Day Out (1990)

Retrying:   9%|▉         | 7/78 [00:07<01:13,  1.04s/it]

  ✓ Recovered: Houseguest (1994)  →  Houseguest (1995)

Retrying:  10%|█         | 8/78 [00:08<01:11,  1.02s/it]

  ✓ Recovered: Heavyweights (1994)  →  Heavyweights (1995)

Retrying:  12%|█▏        | 9/78 [00:09<01:07,  1.03it/s]

  ✓ Recovered: Red Rock West (1992)  →  Red Rock West (1993)

Retrying:  13%|█▎        | 10/78 [00:10<01:03,  1.06it/s]

  ✓ Recovered: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)  →  Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)

Retrying:  14%|█▍        | 11/78 [00:10<00:52,  1.27it/s]

  ✗ Still no match: Stephen King's The Langoliers (1995)

Retrying:  15%|█▌        | 12/78 [00:11<00:54,  1.22it/s]

  ✓ Recovered: Daniel Defoe's Robinson Crusoe (1996)  →  Robinson Crusoe (1997)

Retrying:  17%|█▋        | 13/78 [00:12<00:55,  1.16it/s]

  ✓ Recovered: Conan the Barbarian (1981)  →  Conan the Barbarian (1982)

Retrying:  18%|█▊        | 14/78 [00:13<00:57,  1.12it/s]

  ✓ Recovered: Canadian Bacon (1994)  →  Canadian Bacon (1995)

Retrying:  19%|█▉        | 15/78 [00:14<00:55,  1.13it/s]

  ✓ Recovered: Mute Witness (1994)  →  Mute Witness (1995)

Retrying:  21%|██        | 16/78 [00:15<00:55,  1.13it/s]

  ✓ Recovered: Beyond Bedlam (1993)  →  Beyond Bedlam (1994)

Retrying:  22%|██▏       | 17/78 [00:16<00:54,  1.12it/s]

  ✓ Recovered: Swimming with Sharks (1995)  →  Swimming with Sharks (1994)

Retrying:  23%|██▎       | 18/78 [00:17<00:54,  1.10it/s]

  ✓ Recovered: Boys Life (1995)  →  Bad Boys for Life (2020)

Retrying:  24%|██▍       | 19/78 [00:18<00:53,  1.11it/s]

  ✓ Recovered: Power 98 (1995)  →  Power 98 (1996)

Retrying:  26%|██▌       | 20/78 [00:19<00:52,  1.12it/s]

  ✓ Recovered: Loch Ness (1995)  →  Loch Ness (1996)

Retrying:  27%|██▋       | 21/78 [00:19<00:51,  1.11it/s]

  ✓ Recovered: Two or Three Things I Know About Her (1966)  →  2 or 3 Things I Know About Her (1967)

Retrying:  28%|██▊       | 22/78 [00:20<00:50,  1.11it/s]

  ✓ Recovered: Nosferatu a Venezia (1986)  →  Nosferatu in Venice (1988)

Retrying:  29%|██▉       | 23/78 [00:21<00:49,  1.12it/s]

  ✓ Recovered: Hearts and Minds (1996)  →  Hearts and Minds (1974)

Retrying:  31%|███       | 24/78 [00:22<00:49,  1.10it/s]

  ✓ Recovered: Time Tracers (1995)  →  Time Tracers (1997)

Retrying:  32%|███▏      | 25/78 [00:23<00:41,  1.28it/s]

  ✗ Still no match: U.S. Marshalls (1998)

Retrying:  33%|███▎      | 26/78 [00:24<00:42,  1.24it/s]

  ✓ Recovered: Some Folks Call It a Sling Blade (1993)  →  Some Folks Call It a Sling Blade (1994)

Retrying:  35%|███▍      | 27/78 [00:24<00:42,  1.20it/s]

  ✓ Recovered: Shiloh (1997)  →  Shiloh (1996)

Retrying:  36%|███▌      | 28/78 [00:25<00:42,  1.18it/s]

  ✓ Recovered: Lay of the Land, The (1997)  →  Lay of the Land (1998)

Retrying:  37%|███▋      | 29/78 [00:26<00:43,  1.13it/s]

  ✓ Recovered: Celestial Clockwork (1994)  →  Celestial Clockwork (1995)

Retrying:  38%|███▊      | 30/78 [00:27<00:42,  1.13it/s]

  ✓ Recovered: It's My Party (1995)  →  It's My Party (1996)

Retrying:  40%|███▉      | 31/78 [00:28<00:41,  1.13it/s]

  ✓ Recovered: Bloodsport 2 (1995)  →  Bloodsport II (1996)

Retrying:  41%|████      | 32/78 [00:29<00:41,  1.12it/s]

  ✓ Recovered: Jupiter's Wife (1994)  →  Jupiter's Wife (1995)

Retrying:  42%|████▏     | 33/78 [00:30<00:41,  1.09it/s]

  ✓ Recovered: Backbeat (1993)  →  Backbeat (1994)

Retrying:  44%|████▎     | 34/78 [00:31<00:40,  1.08it/s]

  ✓ Recovered: Major Payne (1994)  →  Major Payne (1995)

Retrying:  45%|████▍     | 35/78 [00:32<00:39,  1.09it/s]

  ✓ Recovered: Boys of St. Vincent, The (1993)  →  The Boys of St. Vincent (1994)

Retrying:  46%|████▌     | 36/78 [00:32<00:32,  1.29it/s]

  ✗ Still no match: Marlene Dietrich: Shadow and Light (1996)

Retrying:  47%|████▋     | 37/78 [00:33<00:33,  1.23it/s]

  ✓ Recovered: Poison Ivy II (1995)  →  Poison Ivy 2: Lily (1996)

Retrying:  49%|████▊     | 38/78 [00:34<00:27,  1.43it/s]

  ✗ Still no match: Big Bang Theory, The (1994)

Retrying:  50%|█████     | 39/78 [00:35<00:29,  1.30it/s]

  ✓ Recovered: Bread and Chocolate (Pane e cioccolata) (1973)  →  Bread and Chocolate (1974)

Retrying:  51%|█████▏    | 40/78 [00:35<00:30,  1.25it/s]

  ✓ Recovered: Ayn Rand: A Sense of Life (1997)  →  Ayn Rand: A Sense of Life (1998)

Retrying:  53%|█████▎    | 41/78 [00:36<00:30,  1.21it/s]

  ✓ Recovered: New York Cop (1996)  →  New York Undercover Cop (1993)

Retrying:  54%|█████▍    | 42/78 [00:37<00:30,  1.19it/s]

  ✓ Recovered: Delta of Venus (1994)  →  Delta of Venus (1995)

Retrying:  55%|█████▌    | 43/78 [00:38<00:29,  1.18it/s]

  ✓ Recovered: Carmen Miranda: Bananas Is My Business (1994)  →  Carmen Miranda: Bananas Is My Business (1995)

Retrying:  56%|█████▋    | 44/78 [00:39<00:29,  1.15it/s]

  ✓ Recovered: Low Life, The (1994)  →  The Low Life (1995)

Retrying:  58%|█████▊    | 45/78 [00:40<00:28,  1.15it/s]

  ✓ Recovered: Last Klezmer: Leopold Kozlowski, His Life and Music, The (1995)  →  The Last Klezmer: Leopold Kozlowski, His Life and Music (1994)

Retrying:  59%|█████▉    | 46/78 [00:41<00:28,  1.14it/s]

  ✓ Recovered: Story of Xinghua, The (1993)  →  The Story of Xinghua (1994)

Retrying:  60%|██████    | 47/78 [00:41<00:23,  1.33it/s]

  ✗ Still no match: Day the Sun Turned Cold, The (Tianguo niezi) (1994)

Retrying:  62%|██████▏   | 48/78 [00:42<00:24,  1.22it/s]

  ✓ Recovered: For the Moment (1994)  →  For the Moment (1993)

Retrying:  63%|██████▎   | 49/78 [00:43<00:24,  1.17it/s]

  ✓ Recovered: The Deadly Cure (1996)  →  The Deadly Cure (1993)

Retrying:  64%|██████▍   | 50/78 [00:44<00:20,  1.36it/s]

  ✗ Still no match: Boys in Venice (1996)

Retrying:  65%|██████▌   | 51/78 [00:44<00:21,  1.27it/s]

  ✓ Recovered: Forbidden Christ, The (Cristo proibito, Il) (1950)  →  The Forbidden Christ (1951)

Retrying:  67%|██████▋   | 52/78 [00:45<00:21,  1.23it/s]

  ✓ Recovered: Hurricane Streets (1998)  →  Hurricane Streets (1997)

Retrying:  68%|██████▊   | 53/78 [00:46<00:20,  1.20it/s]

  ✓ Recovered: Ciao, Professore! (1993)  →  Ciao, Professore! (1992)

Retrying:  69%|██████▉   | 54/78 [00:47<00:17,  1.40it/s]

  ✗ Still no match: Boy's Life 2 (1997)

Retrying:  71%|███████   | 55/78 [00:47<00:14,  1.57it/s]

  ✗ Still no match: Land Before Time III: The Time of the Great Giving (1995) (V)

Retrying:  72%|███████▏  | 56/78 [00:48<00:13,  1.63it/s]

  ✗ Still no match: Gilligan's Island: The Movie (1998)

Retrying:  73%|███████▎  | 57/78 [00:49<00:14,  1.41it/s]

  ✓ Recovered: Men of Means (1998)  →  Men of Means (1999)

Retrying:  74%|███████▍  | 58/78 [00:49<00:15,  1.31it/s]

  ✓ Recovered: Nina Takes a Lover (1994)  →  Nina Takes a Lover (1995)

Retrying:  76%|███████▌  | 59/78 [00:50<00:15,  1.26it/s]

  ✓ Recovered: Jerky Boys, The (1994)  →  The Jerky Boys (1995)

Retrying:  77%|███████▋  | 60/78 [00:51<00:15,  1.20it/s]

  ✓ Recovered: Farmer & Chase (1995)  →  Farmer & Chase (1997)

Retrying:  78%|███████▊  | 61/78 [00:52<00:12,  1.41it/s]

  ✗ Still no match: Aiqing wansui (1994)

Retrying:  79%|███████▉  | 62/78 [00:53<00:12,  1.31it/s]

  ✓ Recovered: Being Human (1993)  →  Being Human (1994)

Retrying:  81%|████████  | 63/78 [00:54<00:12,  1.23it/s]

  ✓ Recovered: Hostile Intentions (1994)  →  Hostile Intentions (1995)

Retrying:  82%|████████▏ | 64/78 [00:54<00:11,  1.20it/s]

  ✓ Recovered: Promise, The (Versprechen, Das) (1994)  →  The False Promise of Advancement (2025)

Retrying:  83%|████████▎ | 65/78 [00:55<00:11,  1.12it/s]

  ✓ Recovered: Vermont Is For Lovers (1992)  →  Vermont Is for Lovers (1993)

Retrying:  85%|████████▍ | 66/78 [00:56<00:09,  1.31it/s]

  ✗ Still no match: Vie est belle, La (Life is Rosey) (1987)

Retrying:  86%|████████▌ | 67/78 [00:57<00:08,  1.24it/s]

  ✓ Recovered: Invitation, The (Zaproszenie) (1986)  →  The Wedding Invitation (2017)

Retrying:  87%|████████▋ | 68/78 [00:57<00:06,  1.43it/s]

  ✗ Still no match: Duoluo tianshi (1995)

Retrying:  88%|████████▊ | 69/78 [00:58<00:06,  1.32it/s]

  ✓ Recovered: Magic Hour, The (1998)  →  The Magic Hour (2008)

Retrying:  90%|████████▉ | 70/78 [00:59<00:06,  1.25it/s]

  ✓ Recovered: Guantanamera (1994)  →  Guantanamera (1995)

Retrying:  91%|█████████ | 71/78 [01:00<00:05,  1.18it/s]

  ✓ Recovered: Hurricane Streets (1998)  →  Hurricane Streets (1997)

Retrying:  92%|█████████▏| 72/78 [01:01<00:05,  1.13it/s]

  ✓ Recovered: Desert Winds (1995)  →  Desert Winds (1994)

Retrying:  94%|█████████▎| 73/78 [01:02<00:04,  1.20it/s]

  ✗ Still no match: Silence of the Palace, The (Saimt el Qusur) (1994)

Retrying:  95%|█████████▍| 74/78 [01:03<00:03,  1.13it/s]

  ✓ Recovered: Á köldum klaka (Cold Fever) (1994)  →  Cold Fever (1995)

Retrying:  96%|█████████▌| 75/78 [01:03<00:02,  1.31it/s]

  ✗ Still no match: Etz Hadomim Tafus (Under the Domin Tree) (1994)

Retrying:  97%|█████████▋| 76/78 [01:04<00:01,  1.49it/s]

  ✗ Still no match: Bitter Sugar (Azucar Amargo) (1996)

Retrying:  99%|█████████▊| 77/78 [01:05<00:00,  1.12it/s]

  ✓ Recovered: Next Step, The (1995)  →  The Next Step (1997)

Retrying: 100%|██████████| 78/78 [01:06<00:00,  1.17it/s]

  ✓ Recovered: Further Gesture, A (1996)  →  A Further Gesture (1997)

Recovered: 62
Still failed: 16
Total matched: 1666 / 1682

## 7. Failed Matches

In [29]:
import os

os.makedirs("../data/enriched", exist_ok=True)
failed_df.to_csv("../data/enriched/failed_matches.csv", index=False)

print(f"Exported {len(failed_df)} failed matches → data/enriched/failed_matches.csv")
display(failed_df)

Exported 16 failed matches → data/enriched/failed_matches.csv

,movieId,raw_title,parsed_title,parsed_year
0,6,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Shanghai Triad (Yao a yao yao dao waipo qiao),1995.0
1,563,Stephen King's The Langoliers (1995),Stephen King's The Langoliers,1995.0
2,912,U.S. Marshalls (1998),U.S. Marshalls,1998.0
3,1201,Marlene Dietrich: Shadow and Light (1996),Marlene Dietrich: Shadow and Light,1996.0
4,1235,"Big Bang Theory, The (1994)",The Big Bang Theory,1994.0
5,1345,"Day the Sun Turned Cold, The (Tianguo niezi) (...","Day the Sun Turned Cold, The (Tianguo niezi)",1994.0
6,1359,Boys in Venice (1996),Boys in Venice,1996.0
7,1405,Boy's Life 2 (1997),Boy's Life 2,1997.0
8,1412,Land Before Time III: The Time of the Great Gi...,Land Before Time III: The Time of the Great Gi...,NaN
9,1420,Gilligan's Island: The Movie (1998),Gilligan's Island: The Movie,1998.0
10,1536,Aiqing wansui (1994),Aiqing wansui,1994.0
11,1569,"Vie est belle, La (Life is Rosey) (1987)","Vie est belle, La (Life is Rosey)",1987.0
12,1591,Duoluo tianshi (1995),Duoluo tianshi,1995.0
13,1630,"Silence of the Palace, The (Saimt el Qusur) (1...","Silence of the Palace, The (Saimt el Qusur)",1994.0
14,1634,Etz Hadomim Tafus (Under the Domin Tree) (1994),Etz Hadomim Tafus (Under the Domin Tree),1994.0
15,1639,Bitter Sugar (Azucar Amargo) (1996),Bitter Sugar (Azucar Amargo),1996.0

## 8. Manual Mapping

In [32]:
# Movies still needing a manual TMDB ID
display(failed_df[["movieId", "raw_title", "parsed_title"]].reset_index(drop=True))

,movieId,raw_title,parsed_title
0,6,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Shanghai Triad (Yao a yao yao dao waipo qiao)
1,563,Stephen King's The Langoliers (1995),Stephen King's The Langoliers
2,912,U.S. Marshalls (1998),U.S. Marshalls
3,1201,Marlene Dietrich: Shadow and Light (1996),Marlene Dietrich: Shadow and Light
4,1235,"Big Bang Theory, The (1994)",The Big Bang Theory
5,1345,"Day the Sun Turned Cold, The (Tianguo niezi) (...","Day the Sun Turned Cold, The (Tianguo niezi)"
6,1359,Boys in Venice (1996),Boys in Venice
7,1405,Boy's Life 2 (1997),Boy's Life 2
8,1412,Land Before Time III: The Time of the Great Gi...,Land Before Time III: The Time of the Great Gi...
9,1420,Gilligan's Island: The Movie (1998),Gilligan's Island: The Movie
10,1536,Aiqing wansui (1994),Aiqing wansui
11,1569,"Vie est belle, La (Life is Rosey) (1987)","Vie est belle, La (Life is Rosey)"
12,1591,Duoluo tianshi (1995),Duoluo tianshi
13,1630,"Silence of the Palace, The (Saimt el Qusur) (1...","Silence of the Palace, The (Saimt el Qusur)"
14,1634,Etz Hadomim Tafus (Under the Domin Tree) (1994),Etz Hadomim Tafus (Under the Domin Tree)
15,1639,Bitter Sugar (Azucar Amargo) (1996),Bitter Sugar (Azucar Amargo)

In [65]:
# Look up each movie at themoviedb.org — the ID is the number in the URL:
# themoviedb.org/movie/862-toy-story  →  862
#
# Fill in one entry per movie, then run this cell.

manual_mapping = [
    {"movieId": 6, "tmdb_id": 37557},
    {"movieId": 912, "tmdb_id": 11808},
    {"movieId": 1201, "tmdb_id": 581579},
    {"movieId": 1345, "tmdb_id": 48144},
    {"movieId": 1405, "tmdb_id": 50091},
    {"movieId": 1412, "tmdb_id": 19004},
    {"movieId": 1420, "tmdb_id": 32677},
    {"movieId": 1536, "tmdb_id": 11985},
    {"movieId": 1569, "tmdb_id": 202425},
    {"movieId": 1591, "tmdb_id": 11220},
    {"movieId": 1630, "tmdb_id": 44284},
    {"movieId": 1633, "tmdb_id": 68445},
    {"movieId": 1634, "tmdb_id": 117730},
    {"movieId": 1639, "tmdb_id": 43777},    
]

In [66]:
manual_enriched = []

for entry in tqdm(manual_mapping, desc="Manual mapping"):
    tmdb_id = entry["tmdb_id"]
    movie   = tmdb_get(f"movie/{tmdb_id}")
    time.sleep(SLEEP_SECONDS)
    credits = tmdb_get(f"movie/{tmdb_id}/credits")
    time.sleep(SLEEP_SECONDS)

    print(f"  ✓ {movie['title']} ({movie.get('release_date', '')[:4]})")
    manual_enriched.append({
        "movieId":   entry["movieId"],
        "raw_title": movie["title"],
        "tmdb_id":   tmdb_id,
        "genre_ids": [g["id"] for g in movie.get("genres", [])],
        "cast":      [m["name"] for m in credits.get("cast", [])[:10]],
        "directors": [m["name"] for m in credits.get("crew", []) if m["job"] == "Director"],
        "matched":   True,
    })

# Merge back into enriched_df
manual_df = pd.DataFrame(manual_enriched)
mapped_ids = set(manual_df["movieId"])
enriched_df = pd.concat([
    enriched_df[~enriched_df["movieId"].isin(mapped_ids)],
    manual_df
]).sort_values("movieId").reset_index(drop=True)

print(f"\nManually mapped: {len(manual_enriched)}")
print(f"Total matched:   {enriched_df['matched'].sum()} / {len(enriched_df)}")

Manual mapping:   7%|▋         | 1/14 [00:00<00:10,  1.19it/s]

  ✓ Shanghai Triad (1995)

Manual mapping:  14%|█▍        | 2/14 [00:01<00:09,  1.21it/s]

  ✓ U.S. Marshals (1998)

Manual mapping:  21%|██▏       | 3/14 [00:02<00:09,  1.22it/s]

  ✓ Marlene Dietrich: Shadows and Light (1996)

Manual mapping:  29%|██▊       | 4/14 [00:03<00:08,  1.22it/s]

  ✓ The Day the Sun Turned Cold (1994)

Manual mapping:  36%|███▌      | 5/14 [00:04<00:07,  1.20it/s]

  ✓ Boys Life 2 (1997)

Manual mapping:  43%|████▎     | 6/14 [00:04<00:06,  1.21it/s]

  ✓ The Land Before Time III: The Time of the Great Giving (1995)

Manual mapping:  50%|█████     | 7/14 [00:05<00:05,  1.22it/s]

  ✓ Rescue from Gilligan's Island (1978)

Manual mapping:  57%|█████▋    | 8/14 [00:06<00:04,  1.23it/s]

  ✓ Vive L'Amour (1995)

Manual mapping:  64%|██████▍   | 9/14 [00:07<00:04,  1.24it/s]

  ✓ Life Is Rosy (1987)

Manual mapping:  71%|███████▏  | 10/14 [00:08<00:03,  1.21it/s]

  ✓ Fallen Angels (1995)

Manual mapping:  79%|███████▊  | 11/14 [00:09<00:02,  1.22it/s]

  ✓ The Silences of the Palace (1994)

Manual mapping:  86%|████████▌ | 12/14 [00:09<00:01,  1.22it/s]

  ✓ Cold Fever (1995)

Manual mapping:  93%|█████████▎| 13/14 [00:10<00:00,  1.23it/s]

  ✓ Under The Domim Tree (1994)

Manual mapping: 100%|██████████| 14/14 [00:11<00:00,  1.23it/s]

  ✓ Bitter Sugar (1996)

Manually mapped: 14
Total matched:   1679 / 1682

## 9. Save Enriched Dataset

In [72]:
# Build genre id → name lookup from Section 1
genre_map = {g["id"]: g["name"] for g in genres["genres"]}

enriched_df["genre_names"] = enriched_df["genre_ids"].apply(
    lambda ids: [genre_map.get(i, str(i)) for i in ids]
)

# Save
os.makedirs("../data/enriched", exist_ok=True)
enriched_df.to_csv("../data/enriched/enriched_movies.csv", index=False)

total   = len(enriched_df)
matched = int(enriched_df["matched"].sum())
print(f"Saved → data/enriched/enriched_movies.csv")
print(f"Match rate: {matched} / {total} ({matched / total:.1%})")
display(enriched_df[["movieId", "raw_title", "tmdb_id", "genre_ids", "genre_names", "cast", "directors"]].head(5))

Saved → data/enriched/enriched_movies.csv
Match rate: 1679 / 1682 (99.8%)

,movieId,raw_title,tmdb_id,genre_ids,genre_names,cast,directors
0,1,Toy Story (1995),862.0,"[10751, 35, 16, 12]","[Family, Comedy, Animation, Adventure]","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",[John Lasseter]
1,2,GoldenEye (1995),710.0,"[12, 28, 53]","[Adventure, Action, Thriller]","[Pierce Brosnan, Sean Bean, Izabella Scorupco,...",[Martin Campbell]
2,3,Four Rooms (1995),5.0,[35],[Comedy],"[Tim Roth, Jennifer Beals, David Proval, Ione ...","[Allison Anders, Alexandre Rockwell, Quentin T..."
3,4,Get Shorty (1995),8012.0,"[35, 53, 80]","[Comedy, Thriller, Crime]","[John Travolta, Gene Hackman, Rene Russo, Dann...",[Barry Sonnenfeld]
4,5,Copycat (1995),1710.0,"[53, 80, 9648]","[Thriller, Crime, Mystery]","[Sigourney Weaver, Holly Hunter, Dermot Mulron...",[Jon Amiel]